from .nodes import NODE_CLASS_MAPPINGS as BFS_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as BFS_NODE_DISPLAY_NAME_MAPPINGS
from .ltxv_editanything import NODE_CLASS_MAPPINGS as LTXV_EA_NODE_CLASS_MAPPINGS
from .ltxv_editanything import NODE_DISPLAY_NAME_MAPPINGS as LTXV_EA_NODE_DISPLAY_NAME_MAPPINGS
from .headswap_node import NODE_CLASS_MAPPINGS as HEADSWAP_NODE_CLASS_MAPPINGS
from .headswap_node import NODE_DISPLAY_NAME_MAPPINGS as HEADSWAP_NODE_DISPLAY_NAME_MAPPINGS
from .anime2real_node import NODE_CLASS_MAPPINGS as A2R_NODE_CLASS_MAPPINGS
from .anime2real_node import NODE_DISPLAY_NAME_MAPPINGS as A2R_NODE_DISPLAY_NAME_MAPPINGS
from .amv_guide_node import NODE_CLASS_MAPPINGS as AMV_NODE_CLASS_MAPPINGS
from .amv_guide_node import NODE_DISPLAY_NAME_MAPPINGS as AMV_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **BFS_NODE_CLASS_MAPPINGS,
    **LTXV_EA_NODE_CLASS_MAPPINGS,
    **HEADSWAP_NODE_CLASS_MAPPINGS,
    **A2R_NODE_CLASS_MAPPINGS,
    **AMV_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **BFS_NODE_DISPLAY_NAME_MAPPINGS,
    **LTXV_EA_NODE_DISPLAY_NAME_MAPPINGS,
    **HEADSWAP_NODE_DISPLAY_NAME_MAPPINGS,
    **A2R_NODE_DISPLAY_NAME_MAPPINGS,
    **AMV_NODE_DISPLAY_NAME_MAPPINGS,
}
